/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/sessao": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Quem está logado */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Usuario"];
                    };
                };
                /** @description Erro com a mensagem para o balcão */
                "4XX": {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
            };
        };
        put?: never;
        /** Entrar (grava o cookie de sessão) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["Entrar"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Usuario"];
                    };
                };
                /** @description Erro com a mensagem para o balcão */
                "4XX": {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
            };
        };
        /** Sair */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Sem conteúdo */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Erro com a mensagem para o balcão */
                "4XX": {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessao/senha": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Trocar a própria senha */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["MudarSenha"];
                };
            };
            responses: {
                /** @description Sem conteúdo */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Erro com a mensagem para o balcão */
                "4XX": {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/usuarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Pessoas com acesso */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Usuario"][];
                    };
                };
                /** @description Erro com a mensagem para o balcão */
                "4XX": {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
            };
        };
        put?: never;
        /** Dar acesso a alguém */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["NovoUsuario"];
                };
            };
            responses: {
                /** @description OK */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Usuario"];
                    };
                };
                /** @description Erro com a mensagem para o balcão */
                "4XX": {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dias": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dias de venda */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ResumoDia"][];
                    };
                };
                /** @description Erro com a mensagem para o balcão */
                "4XX": {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
            };
        };
        put?: never;
        /** Abrir dia de venda */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AbrirDia"];
                };
            };
            responses: {
                /** @description OK */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DiaVenda"];
                    };
                };
                /** @description Erro com a mensagem para o balcão */
                "4XX": {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dias/sugestao-producao": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Último, média e sobra média por produto */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SugestaoProducao"][];
                    };
                };
                /** @description Erro com a mensagem para o balcão */
                "4XX": {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dias/relatorio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fotos dos últimos dias fechados */
        get: {
            parameters: {
                query?: {
                    /** @description Quantos dias (1 a 26, padrão 8) */
                    dias?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DiaFechado"][];
                    };
                };
                /** @description Erro com a mensagem para o balcão */
                "4XX": {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dias/{id}/painel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Início do dia */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PainelDoDia"];
                    };
                };
                /** @description Erro com a mensagem para o balcão */
                "4XX": {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dias/{id}/fechamento": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Fechar o dia (somente leitura depois) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Sem conteúdo */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Erro com a mensagem para o balcão */
                "4XX": {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dias/{id}/pedidos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Pedidos do dia */
        get: {
            parameters: {
                query?: {
                    /** @description reservado | retirado | cancelado */
                    retirada?: string;
                    /** @description Nome, telefone ou número */
                    busca?: string;
                };
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Pedido"][];
                    };
                };
                /** @description Erro com a mensagem para o balcão */
                "4XX": {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
            };
        };
        put?: never;
        /** Confirmar reserva (409 com o máximo se não couber) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["NovoPedido"];
                };
            };
            responses: {
                /** @description OK */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Pedido"];
                    };
                };
                /** @description Erro com a mensagem para o balcão */
                "4XX": {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dias/{id}/producao": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Produção, reservados e vendidos */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EstoqueDoProduto"][];
                    };
                };
                /** @description Erro com a mensagem para o balcão */
                "4XX": {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
            };
        };
        /** Salvar produção (409 abaixo do reservado) */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SalvarProducao"];
                };
            };
            responses: {
                /** @description Sem conteúdo */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Erro com a mensagem para o balcão */
                "4XX": {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dias/{id}/producao/historico": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Quem mudou a produção */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AlteracaoProducao"][];
                    };
                };
                /** @description Erro com a mensagem para o balcão */
                "4XX": {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dias/{id}/espera": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista de espera do dia */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EntradaEspera"][];
                    };
                };
                /** @description Erro com a mensagem para o balcão */
                "4XX": {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
            };
        };
        put?: never;
        /** Entrar na lista de espera */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["NovaEspera"];
                };
            };
            responses: {
                /** @description OK */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EntradaEspera"];
                    };
                };
                /** @description Erro com a mensagem para o balcão */
                "4XX": {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dias/{id}/eventos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Tempo real (text/event-stream): disponibilidade-mudou, unidades-liberadas */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Sem conteúdo */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Erro com a mensagem para o balcão */
                "4XX": {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pedidos/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detalhe do pedido */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Pedido"];
                    };
                };
                /** @description Erro com a mensagem para o balcão */
                "4XX": {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Editar itens (409 se não couber) */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["EditarPedido"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Pedido"];
                    };
                };
                /** @description Erro com a mensagem para o balcão */
                "4XX": {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/pedidos/{id}/retirada": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Marcar como retirado */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Pedido"];
                    };
                };
                /** @description Erro com a mensagem para o balcão */
                "4XX": {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pedidos/{id}/pagamento": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Registrar pagamento */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["Pagamento"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Pedido"];
                    };
                };
                /** @description Erro com a mensagem para o balcão */
                "4XX": {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pedidos/{id}/cancelamento": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancelar reserva */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ResultadoCancelamento"];
                    };
                };
                /** @description Erro com a mensagem para o balcão */
                "4XX": {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pedidos/{id}/reativacao": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reativar cancelado (409 se não couber) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Pedido"];
                    };
                };
                /** @description Erro com a mensagem para o balcão */
                "4XX": {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/produtos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Produtos */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Produto"][];
                    };
                };
                /** @description Erro com a mensagem para o balcão */
                "4XX": {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
            };
        };
        put?: never;
        /** Cadastrar produto */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["NovoProduto"];
                };
            };
            responses: {
                /** @description OK */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Produto"];
                    };
                };
                /** @description Erro com a mensagem para o balcão */
                "4XX": {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/produtos/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Mudar preço ou ativar */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["MudarProduto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Produto"];
                    };
                };
                /** @description Erro com a mensagem para o balcão */
                "4XX": {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/clientes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Clientes (com ?telefone=, no máximo um) */
        get: {
            parameters: {
                query?: {
                    /** @description Só dígitos, com DDD */
                    telefone?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ClienteEncontrado"][];
                    };
                };
                /** @description Erro com a mensagem para o balcão */
                "4XX": {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clientes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Histórico do cliente */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HistoricoDoCliente"];
                    };
                };
                /** @description Erro com a mensagem para o balcão */
                "4XX": {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/espera/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Atendido ou desistiu */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["MudarEspera"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EntradaEspera"];
                    };
                };
                /** @description Erro com a mensagem para o balcão */
                "4XX": {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
            };
        };
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Erro: {
            codigo: string;
            mensagem: string;
            produtoId?: string;
            nome?: string;
            solicitado?: number;
            /** @description No 409 quantidade-indisponivel: o máximo que ainda cabe */
            maximo?: number;
            novaProducao?: number;
            minimo?: number;
        };
        Usuario: {
            id: string;
            nome: string;
            email: string;
        };
        Produto: {
            id: string;
            nome: string;
            /** @description Valor em centavos (R$ 55,00 = 5500) */
            preco: number;
            ativo: boolean;
        };
        DiaVenda: {
            id: string;
            /** @description Data do dia de venda, ex.: 2026-10-04 */
            data: string;
            /** @enum {string} */
            status: "aberto" | "encerrado";
        };
        EstoqueDoProduto: {
            produtoId: string;
            nome: string;
            producao: number;
            /** @description Itens de pedidos ainda não retirados */
            reservados: number;
            /** @description Itens de pedidos já retirados */
            vendidos: number;
        };
        ItemPedido: {
            produtoId: string;
            nome: string;
            quantidade: number;
            /** @description Valor em centavos (R$ 55,00 = 5500) */
            precoUnitario: number;
        };
        RegistroDoPedido: {
            reservadoPor?: string;
            reservadoEm?: string;
            retiradoPor?: string;
            retiradoEm?: string;
            canceladoPor?: string;
            canceladoEm?: string;
        };
        Pedido: {
            id: string;
            numero: number;
            diaId: string;
            cliente: {
                nome: string;
                telefone?: string;
            };
            itens: components["schemas"]["ItemPedido"][];
            /** @enum {string} */
            retirada: "reservado" | "retirado" | "cancelado";
            /** @enum {string} */
            pagamento: "pendente" | "pix" | "dinheiro" | "cartao";
            registro?: components["schemas"]["RegistroDoPedido"];
        };
        ResultadoCancelamento: {
            unidadesLiberadas: number;
            clientesAguardando: number;
        };
        ResumoDia: {
            dia: components["schemas"]["DiaVenda"];
            pedidos: number;
            itensDisponiveis: number;
            /** @description Valor em centavos (R$ 55,00 = 5500) */
            faturamento?: number;
            sobras?: number;
        };
        PainelDoDia: {
            dia: components["schemas"]["DiaVenda"];
            estoques: components["schemas"]["EstoqueDoProduto"][];
            pedidos: number;
            itensReservados: number;
            /** @description Valor em centavos (R$ 55,00 = 5500) */
            valorReservado: number;
            aguardandoRetirada: number;
            proximoARetirar?: {
                numero: number;
                cliente: string;
            };
            clientesAguardando: {
                [key: string]: number;
            };
        };
        SugestaoProducao: {
            produtoId: string;
            nome: string;
            ultimo: number;
            media: number;
            sobraMedia: number;
        };
        AlteracaoProducao: {
            produtoId: string;
            de: number;
            para: number;
            em: string;
            usuario: string;
        };
        ClienteEncontrado: {
            id: string;
            nome: string;
            telefone?: string;
            pedidosAnteriores: number;
        };
        HistoricoDoCliente: {
            cliente: components["schemas"]["ClienteEncontrado"];
            /** @description Valor em centavos (R$ 55,00 = 5500) */
            totalGasto: number;
            naoRetirados: number;
            favoritos: {
                produtoId: string;
                nome: string;
                quantidade: number;
            }[];
            pedidos: {
                id: string;
                numero: number;
                diaId: string;
                cliente: {
                    nome: string;
                    telefone?: string;
                };
                itens: components["schemas"]["ItemPedido"][];
                /** @enum {string} */
                retirada: "reservado" | "retirado" | "cancelado";
                /** @enum {string} */
                pagamento: "pendente" | "pix" | "dinheiro" | "cartao";
                registro?: components["schemas"]["RegistroDoPedido"];
                /** @description Data do dia de venda, ex.: 2026-10-04 */
                data: string;
            }[];
        };
        EntradaEspera: {
            id: string;
            diaId: string;
            produtoId: string;
            cliente: {
                nome: string;
                telefone?: string;
            };
            quantidade: number;
            posicao: number;
            /** @enum {string} */
            status: "aguardando" | "atendido" | "desistiu";
        };
        FechamentoDoProduto: {
            produtoId: string;
            nome: string;
            produzidos: number;
            reservados: number;
            retirados: number;
            naoRetirados: number;
            sobras: number;
        };
        DiaFechado: {
            diaId: string;
            /** @description Data do dia de venda, ex.: 2026-10-04 */
            data: string;
            /** @description Valor em centavos (R$ 55,00 = 5500) */
            faturamento: number;
            produtos: components["schemas"]["FechamentoDoProduto"][];
        };
        Entrar: {
            email: string;
            senha: string;
        };
        NovoUsuario: {
            nome: string;
            email: string;
            senha: string;
        };
        MudarSenha: {
            senhaAtual: string;
            novaSenha: string;
        };
        NovoPedido: {
            cliente: {
                nome: string;
                telefone?: string;
            };
            itens: {
                produtoId: string;
                quantidade: number;
            }[];
        };
        EditarPedido: {
            itens: {
                produtoId: string;
                quantidade: number;
            }[];
        };
        Pagamento: {
            /** @enum {string} */
            pagamento: "pendente" | "pix" | "dinheiro" | "cartao";
        };
        AbrirDia: {
            data: string;
            producao: {
                produtoId: string;
                quantidade: number;
            }[];
        };
        SalvarProducao: {
            quantidades: {
                produtoId: string;
                quantidade: number;
            }[];
        };
        NovoProduto: {
            nome: string;
            preco: number;
        };
        MudarProduto: {
            preco?: number;
            ativo?: boolean;
        };
        NovaEspera: {
            produtoId: string;
            cliente: {
                nome: string;
                telefone?: string;
            };
            quantidade: number;
        };
        MudarEspera: {
            /** @enum {string} */
            status: "aguardando" | "atendido" | "desistiu";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
